kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 9000
    protocol: TCP
  extraMounts:
  - hostPath: /
    containerPath: /hostfs
    readOnly: true
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  extraMounts:
  - hostPath: /
    containerPath: /hostfs
    readOnly: true
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  extraMounts:
  - hostPath: /
    containerPath: /hostfs
    readOnly: true
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
